-- ═══════════════════════════════════════════════════════════════════
-- Migration 000: Schema Migrations Tracker
-- ═══════════════════════════════════════════════════════════════════
--
-- Creates the schema_migrations table to track applied migrations.
-- This migration is always run first and is idempotent.

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename TEXT PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Baseline: If this is an existing database (users table exists) but no
-- schema_migrations table, record migrations 001-006 as already applied.
-- This handles the transition for production databases.
-- NOTE: The actual baseline list is generated by deploy.sh from real filenames

COMMENT ON TABLE schema_migrations IS 
    'Tracks which migration files have been applied to this database';
