#!/usr/bin/env python3

# HSK 3.0 Level 1 vocabulary list provided by user
words = [
    "爱", "爱好", "八", "爸爸", "吧", "白", "白天", "百", "班", "半", "半年", "半天", "帮", "帮忙", "包", "包子", "杯", "杯子", "北", "北边", "北京", "本", "本子", "比", "别", "别的", "别人", "病", "病人", "不大", "不对", "不客气", "不用", "不", "菜", "茶", "差", "常", "常常", "唱", "唱歌", "车", "车票", "车上", "车站", "吃", "吃饭", "出", "出来", "出去", "穿", "床", "次", "从", "错", "打", "打车", "打电话", "打开", "打球", "大", "大学", "大学生", "到", "得到", "地", "的", "等", "地", "地点", "地方", "地上", "地图", "弟弟", "第", "点", "电", "电话", "电脑", "电视", "电视机", "电影", "电影院", "东", "东边", "东西", "动", "动作", "都", "读", "读书", "对", "对不起", "多", "多少", "饿", "儿子", "二", "饭", "饭店", "房间", "房子", "放", "放假", "放学", "飞", "飞机", "非常", "分", "风", "干", "干净", "干", "干什么", "高", "高兴", "告诉", "哥哥", "歌", "个", "给", "跟", "工人", "工作", "关", "关上", "贵", "国", "国家", "国外", "过", "还", "还是", "还有", "孩子", "汉语", "汉字", "好", "好吃", "好看", "好听", "好玩儿", "号", "喝", "和", "很", "后", "后边", "后天", "花", "话", "坏", "还", "回", "回答", "回到", "回家", "回来", "回去", "会", "火车", "机场", "机票", "鸡蛋", "几", "记", "记得", "记住", "家", "家里", "家人", "间", "见", "见面", "教", "叫", "教学楼", "姐姐", "介绍", "今年", "今天", "进", "进来", "进去", "九", "就", "觉得", "开", "开车", "开会", "开玩笑", "看", "看病", "看到", "看见", "考", "考试", "渴", "课", "课本", "课文", "口", "块", "快", "来", "来到", "老", "老人", "老师", "了", "累", "冷", "里", "里边", "两", "零", "六", "楼", "楼上", "楼下", "路", "路口", "路上", "妈妈", "马路", "马上", "吗", "买", "慢", "忙", "毛", "没", "没关系", "没什么", "没事儿", "没有", "妹妹", "门", "门口", "门票", "们", "米饭", "面包", "面条儿", "名字", "明白", "明年", "明天", "拿", "哪", "哪里", "哪儿", "哪些", "那", "那边", "那里", "那儿", "那些", "奶", "奶奶", "男", "男孩儿", "男朋友", "男人", "男生", "南", "南边", "难", "呢", "能", "你", "你们", "年", "您", "牛奶", "女", "女儿", "女孩儿", "女朋友", "女人", "女生", "旁边", "跑", "朋友", "票", "七", "起", "起床", "起来", "汽车", "前", "前边", "前天", "钱", "钱包", "请", "请假", "请进", "请问", "请坐", "球", "去", "去年", "热", "人", "认识", "认真", "日", "日期", "肉", "三", "山", "商场", "商店", "上", "上班", "上边", "上车", "上次", "上课", "上网", "上午", "上学", "少", "谁", "身上", "身体", "什么", "生病", "生气", "生日", "十", "时候", "时间", "事", "试", "是", "是不是", "手", "手机", "书", "书包", "书店", "树", "水", "水果", "睡", "睡觉", "说", "说话", "四", "送", "岁", "他", "他们", "她", "她们", "太", "天", "天气", "听", "听到", "听见", "听写", "同学", "图书馆", "外", "外边", "外国", "外语", "玩儿", "晚", "晚饭", "晚上", "网上", "网友", "忘", "忘记", "问", "我", "我们", "五", "午饭", "西", "西边", "洗", "洗手间", "喜欢", "下", "下班", "下边", "下车", "下次", "下课", "下午", "下雨", "先", "先生", "现在", "想", "小", "小孩儿", "小姐", "小朋友", "小时", "小学", "小学生", "笑", "写", "谢谢", "新", "新年", "星期", "星期日", "星期天", "行", "休息", "学", "学生", "学习", "学校", "学院", "要", "爷爷", "也", "页", "一", "衣服", "医生", "医院", "一半", "一会儿", "一块儿", "一下儿", "一样", "一边", "一点儿", "一起", "一些", "用", "有", "有的", "有名", "有时候", "有", "有用", "右", "右边", "雨", "元", "远", "月", "再", "再见", "在", "在家", "早", "早饭", "早上", "怎么", "站", "找", "找到", "这", "这边", "这里", "这儿", "这些", "着", "真", "真的", "正", "正在", "知道", "知识", "中", "中国", "中间", "中文", "中午", "中学", "中学生", "重", "重要", "住", "准备", "桌子", "字", "子", "走", "走路", "最", "最好", "最后", "昨天", "左", "左边", "坐", "坐下", "做"
]

# Basic pinyin and English translations (simplified)
translations = {
    "爱": ("ài", "love"),
    "爱好": ("ài hào", "hobby"),
    "八": ("bā", "eight"),
    "爸爸": ("bà ba", "father"),
    "吧": ("ba", "particle"),
    "白": ("bái", "white"),
    "白天": ("bái tiān", "daytime"),
    "百": ("bǎi", "hundred"),
    "班": ("bān", "class"),
    "半": ("bàn", "half"),
    "半年": ("bàn nián", "half year"),
    "半天": ("bàn tiān", "half day"),
    "帮": ("bāng", "help"),
    "帮忙": ("bāng máng", "help"),
    "包": ("bāo", "bag"),
    "包子": ("bāo zi", "steamed bun"),
    "杯": ("bēi", "cup"),
    "杯子": ("bēi zi", "cup"),
    "北": ("běi", "north"),
    "北边": ("běi biān", "north side"),
    "北京": ("běi jīng", "Beijing"),
    "本": ("běn", "measure word for books"),
    "本子": ("běn zi", "notebook"),
    "比": ("bǐ", "compare"),
    "别": ("bié", "don't"),
    "别的": ("bié de", "other"),
    "别人": ("bié rén", "other people"),
    "病": ("bìng", "sick"),
    "病人": ("bìng rén", "patient"),
    "不大": ("bù dà", "not big"),
    "不对": ("bù duì", "wrong"),
    "不客气": ("bù kè qì", "you're welcome"),
    "不用": ("bù yòng", "no need"),
    "不": ("bù", "not"),
    "菜": ("cài", "vegetable"),
    "茶": ("chá", "tea"),
    "差": ("chà", "bad"),
    "常": ("cháng", "often"),
    "常常": ("cháng cháng", "often"),
    "唱": ("chàng", "sing"),
    "唱歌": ("chàng gē", "sing"),
    "车": ("chē", "car"),
    "车票": ("chē piào", "ticket"),
    "车上": ("chē shàng", "on the car"),
    "车站": ("chē zhàn", "station"),
    "吃": ("chī", "eat"),
    "吃饭": ("chī fàn", "eat"),
    "出": ("chū", "go out"),
    "出来": ("chū lái", "come out"),
    "出去": ("chū qù", "go out"),
    "穿": ("chuān", "wear"),
    "床": ("chuáng", "bed"),
    "次": ("cì", "time"),
    "从": ("cóng", "from"),
    "错": ("cuò", "wrong"),
    "打": ("dǎ", "hit"),
    "打车": ("dǎ chē", "take a taxi"),
    "打电话": ("dǎ diàn huà", "make a phone call"),
    "打开": ("dǎ kāi", "open"),
    "打球": ("dǎ qiú", "play ball"),
    "大": ("dà", "big"),
    "大学": ("dà xué", "university"),
    "大学生": ("dà xué shēng", "university student"),
    "到": ("dào", "arrive"),
    "得到": ("dé dào", "get"),
    "地": ("de", "particle"),
    "的": ("de", "particle"),
    "等": ("děng", "wait"),
    "地点": ("dì diǎn", "location"),
    "地方": ("dì fang", "place"),
    "地上": ("dì shàng", "on the ground"),
    "地图": ("dì tú", "map"),
    "弟弟": ("dì di", "younger brother"),
    "第": ("dì", "ordinal prefix"),
    "点": ("diǎn", "point"),
    "电": ("diàn", "electricity"),
    "电话": ("diàn huà", "telephone"),
    "电脑": ("diàn nǎo", "computer"),
    "电视": ("diàn shì", "television"),
    "电视机": ("diàn shì jī", "television"),
    "电影": ("diàn yǐng", "movie"),
    "电影院": ("diàn yǐng yuàn", "cinema"),
    "东": ("dōng", "east"),
    "东边": ("dōng biān", "east side"),
    "东西": ("dōng xī", "thing"),
    "动": ("dòng", "move"),
    "动作": ("dòng zuò", "action"),
    "都": ("dōu", "all"),
    "读": ("dú", "read"),
    "读书": ("dú shū", "study"),
    "对": ("duì", "correct"),
    "对不起": ("duì bù qǐ", "sorry"),
    "多": ("duō", "many"),
    "多少": ("duō shao", "how much"),
    "饿": ("è", "hungry"),
    "儿子": ("ér zi", "son"),
    "二": ("èr", "two"),
    "饭": ("fàn", "rice"),
    "饭店": ("fàn diàn", "restaurant"),
    "房间": ("fáng jiān", "room"),
    "房子": ("fáng zi", "house"),
    "放": ("fàng", "put"),
    "放假": ("fàng jià", "holiday"),
    "放学": ("fàng xué", "school is over"),
    "飞": ("fēi", "fly"),
    "飞机": ("fēi jī", "airplane"),
    "非常": ("fēi cháng", "very"),
    "分": ("fēn", "minute"),
    "风": ("fēng", "wind"),
    "干": ("gān", "dry"),
    "干净": ("gān jìng", "clean"),
    "干什么": ("gàn shén me", "what to do"),
    "高": ("gāo", "high"),
    "高兴": ("gāo xìng", "happy"),
    "告诉": ("gào sù", "tell"),
    "哥哥": ("gē ge", "older brother"),
    "歌": ("gē", "song"),
    "个": ("gè", "measure word"),
    "给": ("gěi", "give"),
    "跟": ("gēn", "with"),
    "工人": ("gōng rén", "worker"),
    "工作": ("gōng zuò", "work"),
    "关": ("guān", "close"),
    "关上": ("guān shàng", "close"),
    "贵": ("guì", "expensive"),
    "国": ("guó", "country"),
    "国家": ("guó jiā", "country"),
    "国外": ("guó wài", "abroad"),
    "过": ("guò", "pass"),
    "还": ("hái", "still"),
    "还是": ("hái shì", "still"),
    "还有": ("hái yǒu", "also have"),
    "孩子": ("hái zi", "child"),
    "汉语": ("hàn yǔ", "Chinese language"),
    "汉字": ("hàn zì", "Chinese character"),
    "好": ("hǎo", "good"),
    "好吃": ("hǎo chī", "delicious"),
    "好看": ("hǎo kàn", "good-looking"),
    "好听": ("hǎo tīng", "pleasant to hear"),
    "好玩儿": ("hǎo wánr", "fun"),
    "号": ("hào", "number"),
    "喝": ("hē", "drink"),
    "和": ("hé", "and"),
    "很": ("hěn", "very"),
    "后": ("hòu", "after"),
    "后边": ("hòu biān", "behind"),
    "后天": ("hòu tiān", "day after tomorrow"),
    "花": ("huā", "flower"),
    "话": ("huà", "word"),
    "坏": ("huài", "bad"),
    "回": ("huí", "return"),
    "回答": ("huí dá", "answer"),
    "回到": ("huí dào", "return to"),
    "回家": ("huí jiā", "go home"),
    "回来": ("huí lái", "come back"),
    "回去": ("huí qù", "go back"),
    "会": ("huì", "can"),
    "火车": ("huǒ chē", "train"),
    "机场": ("jī chǎng", "airport"),
    "机票": ("jī piào", "air ticket"),
    "鸡蛋": ("jī dàn", "egg"),
    "几": ("jǐ", "how many"),
    "记": ("jì", "remember"),
    "记得": ("jì de", "remember"),
    "记住": ("jì zhù", "remember"),
    "家": ("jiā", "home"),
    "家里": ("jiā lǐ", "at home"),
    "家人": ("jiā rén", "family"),
    "间": ("jiān", "between"),
    "见": ("jiàn", "see"),
    "见面": ("jiàn miàn", "meet"),
    "教": ("jiāo", "teach"),
    "叫": ("jiào", "call"),
    "教学楼": ("jiào xué lóu", "teaching building"),
    "姐姐": ("jiě jie", "older sister"),
    "介绍": ("jiè shào", "introduce"),
    "今年": ("jīn nián", "this year"),
    "今天": ("jīn tiān", "today"),
    "进": ("jìn", "enter"),
    "进来": ("jìn lái", "come in"),
    "进去": ("jìn qù", "go in"),
    "九": ("jiǔ", "nine"),
    "就": ("jiù", "just"),
    "觉得": ("jué de", "feel"),
    "开": ("kāi", "open"),
    "开车": ("kāi chē", "drive"),
    "开会": ("kāi huì", "have a meeting"),
    "开玩笑": ("kāi wán xiào", "joke"),
    "看": ("kàn", "look"),
    "看病": ("kàn bìng", "see a doctor"),
    "看到": ("kàn dào", "see"),
    "看见": ("kàn jiàn", "see"),
    "考": ("kǎo", "test"),
    "考试": ("kǎo shì", "exam"),
    "渴": ("kě", "thirsty"),
    "课": ("kè", "class"),
    "课本": ("kè běn", "textbook"),
    "课文": ("kè wén", "text"),
    "口": ("kǒu", "mouth"),
    "块": ("kuài", "piece"),
    "快": ("kuài", "fast"),
    "来": ("lái", "come"),
    "来到": ("lái dào", "arrive"),
    "老": ("lǎo", "old"),
    "老人": ("lǎo rén", "old person"),
    "老师": ("lǎo shī", "teacher"),
    "了": ("le", "particle"),
    "累": ("lèi", "tired"),
    "冷": ("lěng", "cold"),
    "里": ("lǐ", "inside"),
    "里边": ("lǐ biān", "inside"),
    "两": ("liǎng", "two"),
    "零": ("líng", "zero"),
    "六": ("liù", "six"),
    "楼": ("lóu", "building"),
    "楼上": ("lóu shàng", "upstairs"),
    "楼下": ("lóu xià", "downstairs"),
    "路": ("lù", "road"),
    "路口": ("lù kǒu", "intersection"),
    "路上": ("lù shàng", "on the road"),
    "妈妈": ("mā ma", "mother"),
    "马路": ("mǎ lù", "road"),
    "马上": ("mǎ shàng", "immediately"),
    "吗": ("ma", "question particle"),
    "买": ("mǎi", "buy"),
    "慢": ("màn", "slow"),
    "忙": ("máng", "busy"),
    "毛": ("máo", "hair"),
    "没": ("méi", "not"),
    "没关系": ("méi guān xì", "it's okay"),
    "没什么": ("méi shén me", "nothing"),
    "没事儿": ("méi shìr", "it's okay"),
    "没有": ("méi yǒu", "don't have"),
    "妹妹": ("mèi mei", "younger sister"),
    "门": ("mén", "door"),
    "门口": ("mén kǒu", "doorway"),
    "门票": ("mén piào", "ticket"),
    "们": ("men", "plural marker"),
    "米饭": ("mǐ fàn", "rice"),
    "面包": ("miàn bāo", "bread"),
    "面条儿": ("miàn tiáor", "noodles"),
    "名字": ("míng zi", "name"),
    "明白": ("míng bai", "understand"),
    "明年": ("míng nián", "next year"),
    "明天": ("míng tiān", "tomorrow"),
    "拿": ("ná", "take"),
    "哪": ("nǎ", "which"),
    "哪里": ("nǎ lǐ", "where"),
    "哪儿": ("nǎr", "where"),
    "哪些": ("nǎ xiē", "which ones"),
    "那": ("nà", "that"),
    "那边": ("nà biān", "over there"),
    "那里": ("nà lǐ", "there"),
    "那儿": ("nàr", "there"),
    "那些": ("nà xiē", "those"),
    "奶": ("nǎi", "milk"),
    "奶奶": ("nǎi nai", "grandmother"),
    "男": ("nán", "male"),
    "男孩儿": ("nán háir", "boy"),
    "男朋友": ("nán péng yǒu", "boyfriend"),
    "男人": ("nán rén", "man"),
    "男生": ("nán shēng", "male student"),
    "南": ("nán", "south"),
    "南边": ("nán biān", "south side"),
    "难": ("nán", "difficult"),
    "呢": ("ne", "particle"),
    "能": ("néng", "can"),
    "你": ("nǐ", "you"),
    "你们": ("nǐ men", "you all"),
    "年": ("nián", "year"),
    "您": ("nín", "you (polite)"),
    "牛奶": ("niú nǎi", "milk"),
    "女": ("nǚ", "female"),
    "女儿": ("nǚ ér", "daughter"),
    "女孩儿": ("nǚ háir", "girl"),
    "女朋友": ("nǚ péng yǒu", "girlfriend"),
    "女人": ("nǚ rén", "woman"),
    "女生": ("nǚ shēng", "female student"),
    "旁边": ("páng biān", "beside"),
    "跑": ("pǎo", "run"),
    "朋友": ("péng yǒu", "friend"),
    "票": ("piào", "ticket"),
    "七": ("qī", "seven"),
    "起": ("qǐ", "rise"),
    "起床": ("qǐ chuáng", "get up"),
    "起来": ("qǐ lái", "get up"),
    "汽车": ("qì chē", "car"),
    "前": ("qián", "front"),
    "前边": ("qián biān", "in front"),
    "前天": ("qián tiān", "day before yesterday"),
    "钱": ("qián", "money"),
    "钱包": ("qián bāo", "wallet"),
    "请": ("qǐng", "please"),
    "请假": ("qǐng jià", "ask for leave"),
    "请进": ("qǐng jìn", "come in"),
    "请问": ("qǐng wèn", "excuse me"),
    "请坐": ("qǐng zuò", "please sit"),
    "球": ("qiú", "ball"),
    "去": ("qù", "go"),
    "去年": ("qù nián", "last year"),
    "热": ("rè", "hot"),
    "人": ("rén", "person"),
    "认识": ("rèn shi", "know"),
    "认真": ("rèn zhēn", "serious"),
    "日": ("rì", "day"),
    "日期": ("rì qī", "date"),
    "肉": ("ròu", "meat"),
    "三": ("sān", "three"),
    "山": ("shān", "mountain"),
    "商场": ("shāng chǎng", "mall"),
    "商店": ("shāng diàn", "shop"),
    "上": ("shàng", "up"),
    "上班": ("shàng bān", "go to work"),
    "上边": ("shàng biān", "above"),
    "上车": ("shàng chē", "get on"),
    "上次": ("shàng cì", "last time"),
    "上课": ("shàng kè", "go to class"),
    "上网": ("shàng wǎng", "go online"),
    "上午": ("shàng wǔ", "morning"),
    "上学": ("shàng xué", "go to school"),
    "少": ("shǎo", "few"),
    "谁": ("shuí", "who"),
    "身上": ("shēn shàng", "on the body"),
    "身体": ("shēn tǐ", "body"),
    "什么": ("shén me", "what"),
    "生病": ("shēng bìng", "get sick"),
    "生气": ("shēng qì", "angry"),
    "生日": ("shēng rì", "birthday"),
    "十": ("shí", "ten"),
    "时候": ("shí hou", "time"),
    "时间": ("shí jiān", "time"),
    "事": ("shì", "matter"),
    "试": ("shì", "try"),
    "是": ("shì", "be"),
    "是不是": ("shì bù shì", "is it"),
    "手": ("shǒu", "hand"),
    "手机": ("shǒu jī", "mobile phone"),
    "书": ("shū", "book"),
    "书包": ("shū bāo", "schoolbag"),
    "书店": ("shū diàn", "bookstore"),
    "树": ("shù", "tree"),
    "水": ("shuǐ", "water"),
    "水果": ("shuǐ guǒ", "fruit"),
    "睡": ("shuì", "sleep"),
    "睡觉": ("shuì jiào", "sleep"),
    "说": ("shuō", "say"),
    "说话": ("shuō huà", "speak"),
    "四": ("sì", "four"),
    "送": ("sòng", "send"),
    "岁": ("suì", "year old"),
    "他": ("tā", "he"),
    "他们": ("tā men", "they"),
    "她": ("tā", "she"),
    "她们": ("tā men", "they"),
    "太": ("tài", "too"),
    "天": ("tiān", "day"),
    "天气": ("tiān qì", "weather"),
    "听": ("tīng", "listen"),
    "听到": ("tīng dào", "hear"),
    "听见": ("tīng jiàn", "hear"),
    "听写": ("tīng xiě", "dictation"),
    "同学": ("tóng xué", "classmate"),
    "图书馆": ("tú shū guǎn", "library"),
    "外": ("wài", "outside"),
    "外边": ("wài biān", "outside"),
    "外国": ("wài guó", "foreign country"),
    "外语": ("wài yǔ", "foreign language"),
    "玩儿": ("wánr", "play"),
    "晚": ("wǎn", "late"),
    "晚饭": ("wǎn fàn", "dinner"),
    "晚上": ("wǎn shang", "evening"),
    "网上": ("wǎng shàng", "online"),
    "网友": ("wǎng yǒu", "online friend"),
    "忘": ("wàng", "forget"),
    "忘记": ("wàng jì", "forget"),
    "问": ("wèn", "ask"),
    "我": ("wǒ", "I"),
    "我们": ("wǒ men", "we"),
    "五": ("wǔ", "five"),
    "午饭": ("wǔ fàn", "lunch"),
    "西": ("xī", "west"),
    "西边": ("xī biān", "west side"),
    "洗": ("xǐ", "wash"),
    "洗手间": ("xǐ shǒu jiān", "bathroom"),
    "喜欢": ("xǐ huān", "like"),
    "下": ("xià", "down"),
    "下班": ("xià bān", "get off work"),
    "下边": ("xià biān", "below"),
    "下车": ("xià chē", "get off"),
    "下次": ("xià cì", "next time"),
    "下课": ("xià kè", "class is over"),
    "下午": ("xià wǔ", "afternoon"),
    "下雨": ("xià yǔ", "rain"),
    "先": ("xiān", "first"),
    "先生": ("xiān sheng", "Mr."),
    "现在": ("xiàn zài", "now"),
    "想": ("xiǎng", "think"),
    "小": ("xiǎo", "small"),
    "小孩儿": ("xiǎo háir", "child"),
    "小姐": ("xiǎo jiě", "Miss"),
    "小朋友": ("xiǎo péng yǒu", "child"),
    "小时": ("xiǎo shí", "hour"),
    "小学": ("xiǎo xué", "primary school"),
    "小学生": ("xiǎo xué shēng", "primary school student"),
    "笑": ("xiào", "laugh"),
    "写": ("xiě", "write"),
    "谢谢": ("xiè xie", "thank you"),
    "新": ("xīn", "new"),
    "新年": ("xīn nián", "New Year"),
    "星期": ("xīng qī", "week"),
    "星期日": ("xīng qī rì", "Sunday"),
    "星期天": ("xīng qī tiān", "Sunday"),
    "行": ("xíng", "okay"),
    "休息": ("xiū xi", "rest"),
    "学": ("xué", "study"),
    "学生": ("xué shēng", "student"),
    "学习": ("xué xí", "study"),
    "学校": ("xué xiào", "school"),
    "学院": ("xué yuàn", "college"),
    "要": ("yào", "want"),
    "爷爷": ("yé ye", "grandfather"),
    "也": ("yě", "also"),
    "页": ("yè", "page"),
    "一": ("yī", "one"),
    "衣服": ("yī fu", "clothes"),
    "医生": ("yī shēng", "doctor"),
    "医院": ("yī yuàn", "hospital"),
    "一半": ("yī bàn", "half"),
    "一会儿": ("yī huìr", "a while"),
    "一块儿": ("yī kuàir", "together"),
    "一下儿": ("yī xiàr", "a bit"),
    "一样": ("yī yàng", "same"),
    "一边": ("yī biān", "one side"),
    "一点儿": ("yī diǎnr", "a little"),
    "一起": ("yī qǐ", "together"),
    "一些": ("yī xiē", "some"),
    "用": ("yòng", "use"),
    "有": ("yǒu", "have"),
    "有的": ("yǒu de", "some"),
    "有名": ("yǒu míng", "famous"),
    "有时候": ("yǒu shí hou", "sometimes"),
    "有用": ("yǒu yòng", "useful"),
    "右": ("yòu", "right"),
    "右边": ("yòu biān", "right side"),
    "雨": ("yǔ", "rain"),
    "元": ("yuán", "yuan"),
    "远": ("yuǎn", "far"),
    "月": ("yuè", "month"),
    "再": ("zài", "again"),
    "再见": ("zài jiàn", "goodbye"),
    "在": ("zài", "at"),
    "在家": ("zài jiā", "at home"),
    "早": ("zǎo", "early"),
    "早饭": ("zǎo fàn", "breakfast"),
    "早上": ("zǎo shang", "morning"),
    "怎么": ("zěn me", "how"),
    "站": ("zhàn", "stand"),
    "找": ("zhǎo", "find"),
    "找到": ("zhǎo dào", "find"),
    "这": ("zhè", "this"),
    "这边": ("zhè biān", "this side"),
    "这里": ("zhè lǐ", "here"),
    "这儿": ("zhèr", "here"),
    "这些": ("zhè xiē", "these"),
    "着": ("zhe", "particle"),
    "真": ("zhēn", "real"),
    "真的": ("zhēn de", "really"),
    "正": ("zhèng", "just"),
    "正在": ("zhèng zài", "in the process of"),
    "知道": ("zhī dào", "know"),
    "知识": ("zhī shi", "knowledge"),
    "中": ("zhōng", "middle"),
    "中国": ("zhōng guó", "China"),
    "中间": ("zhōng jiān", "middle"),
    "中文": ("zhōng wén", "Chinese"),
    "中午": ("zhōng wǔ", "noon"),
    "中学": ("zhōng xué", "middle school"),
    "中学生": ("zhōng xué shēng", "middle school student"),
    "重": ("zhòng", "heavy"),
    "重要": ("zhòng yào", "important"),
    "住": ("zhù", "live"),
    "准备": ("zhǔn bèi", "prepare"),
    "桌子": ("zhuō zi", "table"),
    "字": ("zì", "character"),
    "子": ("zi", "child"),
    "走": ("zǒu", "walk"),
    "走路": ("zǒu lù", "walk"),
    "最": ("zuì", "most"),
    "最好": ("zuì hǎo", "best"),
    "最后": ("zuì hòu", "last"),
    "昨天": ("zuó tiān", "yesterday"),
    "左": ("zuǒ", "left"),
    "左边": ("zuǒ biān", "left side"),
    "坐": ("zuò", "sit"),
    "坐下": ("zuò xià", "sit down"),
    "做": ("zuò", "do")
}

def generate_migration():
    migration_content = """-- Migration: 024_add_complete_hsk_3_0_level_1.sql
-- Add complete HSK 3.0 level 1 vocabulary
-- Based on official HSK 3.0 level 1 word list

INSERT INTO vocabulary (chinese, pinyin, english, hsk_level, example_sentences) VALUES
"""
    
    for word in words:
        if word in translations:
            pinyin, english = translations[word]
            # Create simple example sentences
            example_sentences = f'[{{"chinese": "{word}。", "pinyin": "{pinyin}。", "english": "{english}."}}]'
            
            migration_content += f"""('{word}', '{pinyin}', '{english}', 1, '{example_sentences}'),
"""
    
    # Remove the last comma and add semicolon
    migration_content = migration_content.rstrip(',\n') + ';'
    
    return migration_content

if __name__ == "__main__":
    migration = generate_migration()
    with open('backend/db/migrations/024_add_complete_hsk_3_0_level_1.sql', 'w', encoding='utf-8') as f:
        f.write(migration)
    print("Migration file generated: backend/db/migrations/024_add_complete_hsk_3_0_level_1.sql") 